### DISCUSSION TITLE
how to set publicAccess: true or false for each target using SwiftGen

### DISCUSSION THREAD

**Discussion by tranvutuan** [SwiftGen/SwiftGen#843] [Q&A] [answered]
Currently, an architecture of our app is
```
target A
    --- images
target B
    --- images
target C
   --- images
target Shared ( which will be shared between A and B and C )
   --- images
```

And my swift.gen.yml looks like
```
xcassets:
  inputs: ${PROJECT_DIR}/novus/Resources/${TARGET_NAME}/${TARGET_NAME}.xcassets
  outputs:
    templateName: swift5
    output: ${PROJECT_DIR}/novus/Resources/${TARGET_NAME}/${TARGET_NAME}Images.swift
```
Since I don't use `publicAccess: true` therefore target A and B and C can't access `images` from `Shared` since it is `internal`. 

Is there a way such that can specify only images from `Shared` are `public` but images from A and B and C are still internal for its target
