### DISCUSSION TITLE
Strings: Override default parser separator via CLI or config

### DISCUSSION THREAD

**Discussion by rukano** [SwiftGen/SwiftGen#849] [Q&A] [answered]
At the moment the strings format structured stencil works great when the localisable string keys are separated with `.`. Sadly for some projects using a keying convention for localisable strings is a problem, for example, in the android platform the localisable keys are not allowed to use `.`.

Would it be possible to override the default separator `"."` in the

```swift
  public enum Option {
    static let separator = ParserOption(
      key: "separator",
      defaultValue: ".",
      help: "Separator used to split keys into components"
    )
  }
```

via a config, or via command line when `swiftgen run strings` is called? something like `--separator="_"` or similar? This would give more flexibility to some projects that have a shared codebase for the strings, and some naming conventions that are not handled by `SwiftGen`.

If someone points me out in the right direction to do this, I can create a PR for this. I just don't know the whole SwiftGen's architecture and if this is possible and desired.

SwiftGen 6.4.0
Xcode 15.5

**Comment by djbe** [comment, marked as answer]
As you've already found the option you need, you just need to add it to your configuration file:
```yaml
...
strings:
  inputs:
    - Base.lproj/Localizable.strings
    - Base.lproj/Localizable.stringsdict
  options:
    separator: _
  outputs:
    templateName: structured-swift5
    output: Strings.swift
```

When adding parser options or template parameters, verify your config is correct using `swiftgen config lint` 😉
