### DISCUSSION TITLE
Getting an error due to duplication

### DISCUSSION THREAD

**Discussion by tranvutuan** [SwiftGen/SwiftGen#857] [Q&A]
Im trying to generate images from different paths like following
```
xcassets:
    inputs:
        - ${PROJECT_DIR}/sample/Resources/Folder1/Colors.xcassets
        - ${PROJECT_DIR}/sample/Resources/Folder2/Colors.xcassets
    outputs:
        templateName: swift5
        output: ${PROJECT_DIR}/sample/Resources/Sample/Assets.swift
```

After running `swiftgen config run --config` it generated Assets.swift but there is an error due to duplication
```
// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif

// Deprecated typealiases
@available(*, deprecated, renamed: "ColorAsset.Color", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetColorTypeAlias = ColorAsset.Color
@available(*, deprecated, renamed: "ImageAsset.Image", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetImageTypeAlias = ImageAsset.Image

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
internal enum Asset {
  internal enum Colors { // This group of colors from _Folder1/Colors.xcassets_
    internal static let error1 = ColorAsset(name: "Error1")
    internal static let primary = ColorAsset(name: "Primary")
    internal static let primary2 = ColorAsset(name: "Primary2")
    internal static let primary3 = ColorAsset(name: "Primary3")
    internal static let secondary1 = ColorAsset(name: "Secondary1")
    internal static let secondary2 = ColorAsset(name: "Secondary2")
  }
  internal enum Colors { // This group of colors from _Folder2/Colors.xcassets_
    internal static let neutral1 = ColorAsset(name: "Neutral1")
    internal static let neutral2 = ColorAsset(name: "Neutral2")
    internal static let neutral3 = ColorAsset(name: "Neutral3")
    internal static let neutral4 = ColorAsset(name: "Neutral4")
    internal static let neutral5 = ColorAsset(name: "Neutral5")
    internal static let neutral6 = ColorAsset(name: "Neutral6")
  }
```

Are there ways to merge them into the same enum named `Colors`
