### DISCUSSION TITLE
bundle does not override with params in order to use resource bundle

### DISCUSSION THREAD

**Discussion by anuradhss** [SwiftGen/SwiftGen#866] [Q&A] [answered]
I want to use **resource bundle** instead of default bundle `BundleToken.bundle`. Then I modified `swiftgen.yml` file as below.

`swiftgen.yml`

```
strings:
  inputs:
    - MyFramework/Localizable.strings
  outputs:
    templateName: structured-swift4
    output: MyFramework/Strings.swift
    params:
      bundle: MyFrameworkPodBundle.resourcesBundle
```

And also I created a class inside my framework in order to get the respective resource bundle as below

`MyFrameworkPodBundle.swift`

```

import Foundation

public final class MyFrameworkPodBundle {
  // This is the bundle where your code resides in
  public static let bundle = Bundle(for: MyFrameworkPodBundle.self)

  // Your resources bundle is inside that bundle
  public static let resourcesBundle: Bundle = {
	guard let url = bundle.url(forResource: "MyFrameworkResources", withExtension: "bundle"),
	  let bundle = Bundle(url: url) else {
          fatalError("Can't find 'MyFrameworkPodResources' bundle")
	}
      return bundle
 }()
}
```

And I have my resource bundle named `MyFrameworkResources` in my pod. But every time when `SwiftGen` runs it does not change anything and `bundle` stays the same as below in `Strings.swift` file. And it always to read resources using default bundle which is `BundleToken.bundle`.

`Strings.swift`
```
private final class BundleToken {
  static let bundle: Bundle = {
    Bundle(for: BundleToken.self)
  }()
}
```
I'm using following version.
`SwiftGen v6.4.0 (Stencil v0.13.1, StencilSwiftKit v2.7.2, SwiftGenKit v6.4.0)`

Any idea why this isn't working 🤔 ?
