### DISCUSSION TITLE
How to access with Swiftgen to resources within Swift Package?

### DISCUSSION THREAD

**Discussion by KurroCantos** [SwiftGen/SwiftGen#976] [General]
I want to store all the icon and color catalogs of my app in a local package. In the future I will store all the visual components. I use swiftgen in my app and when I compile it recognizes and generates the catalogs inside the package but then it fails to access the resource.

```Thread 1: Fatal error: Unable to load image named ic_single_pic.```

I think it may be because of Bundle. Can anyone help me?

Thanks

**Comment by djbe** [comment]
Could you please post your configuration, and share how your project is structured?

**Reply by KurroCantos** [reply]
### **Swiftgen configurations:**

```
{{accessModifier}} struct {{imageType}}: Equatable {
  	{{accessModifier}} fileprivate(set) var name: String

  	{{accessModifier}} var image: {{imageAlias}} {
    	let bundle = Bundle(for: BundleToken.self)
    	#if os(iOS) || os(tvOS)
    	let image = {{imageAlias}}(named: name, in: bundle, compatibleWith: nil)
    	#elseif os(OSX)
    	let image = bundle.image(forResource: NSImage.Name(name))
    	#elseif os(watchOS)
    	let image = {{imageAlias}}(named: name)
    	#endif
    	guard let result = image else { fatalError("Unable to load image named \(name).") }
    	return result
  }
}

{{accessModifier}} extension {{imageAlias}} {
  	@available(iOS 1.0, tvOS 1.0, watchOS 1.0, *)
  	@available(OSX, deprecated, message: "This initializer is unsafe on macOS, please use the {{imageType}}.image property")
  	
  	convenience init!(asset: {{imageType}}) {
    	#if os(iOS) || os(tvOS)
    	let bundle = Bundle(for: BundleToken.self)
    	self.init(named: asset.name, in: bundle, compatibleWith: nil)
    	#elseif os(OSX)
    	self.init(named: NSImage.Name(asset.name))
    	#elseif os(watchOS)
    	self.init(named: asset.name)
    	#endif
  	}
}

private final class BundleToken {}
```

### **Local package configuration:**

![Captura de Pantalla 2022-07-30 a las 10 11 36](https://user-images.githubusercontent.com/100117443/181890994-4cf13d59-6b59-4c24-bf97-2a5053968c8d.png)

```
// swift-tools-version: 5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "DesignSystem",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "DesignSystem",
            targets: ["DesignSystem"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "DesignSystem",
            dependencies: []
        ),
        .testTarget(
            name: "DesignSystemTests",
            dependencies: ["DesignSystem"]),
    ]
)
```

**Reply by djbe** [reply]
How are you running SwiftGen? What does your configuration yml look like?

**Reply by KurroCantos** [reply]
Hi @djbe I'm running Swiftgen in the build phases of the project. 
```
if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then
  "${PODS_ROOT}/SwiftGen/bin/swiftgen"
else
  echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
fi
```

And this is the yml configuration: 
```
strings:
  inputs: App/Supporting Files/Localizable/en.lproj/Localizable.strings
  filter: .+\.strings$
  outputs:
    - templatePath: ./templates/Swiftgen/app-localizable.stencil
      output: App/Infrastructure/Resources/L10n.swift

xcassets:
  inputs: 
    - App/Supporting Files/Assets.xcassets
    - App/Supporting Files/Colors.xcassets
    - App/Supporting Files/CustomColors.xcassets
    - App/Infrastructure/UI Components/DesignSystem/Sources/DesignSystem/Assets_DS.xcassets 
    - App/Infrastructure/UI Components/DesignSystem/Sources/DesignSystem/Colors_DS.xcassets
  outputs:
    - templatePath: ./templates/Swiftgen/app-xcassets.stencil
      output: App/Infrastructure/Resources/Assets.swift

fonts:
  inputs: App
  outputs:
    templatePath: ./templates/Swiftgen/app-fonts.stencil
    output: App/Infrastructure/Resources/Fonts.swift
```
