### ISSUE TITLE
Can't have multiple strings config in the same yml file?

### ISSUE THREAD

**Issue by sleimanzublidi** [SwiftGen/SwiftGen#1061]
I tried running swiftgen with a yml config that contain 3 strings configurations but only the last of them is generated. 
No error message is displayed in command line. Why can't I have multiple strings config in the same yml file?
Any help is much appreciated!

```
strings:
  inputs: 
    - en.lproj/LocalizationA.strings
  outputs:  
    - templatePath: strings.stencil
      params:
        className: StringsA
      output: FileA.swift
strings:
  inputs: 
    - en.lproj/LocalizationB.strings
  outputs:  
    - templatePath: strings.stencil
      params:
        className: StringsB
      output: FileB.swift
strings:
  inputs: 
    - en.lproj/LocalizationC.strings
  outputs:  
    - templatePath: strings.stencil
      params:
        className: StringsC
      output: File.swift
```
