### ISSUE TITLE
Nested image assets structure is broken in v6.6.2

### ISSUE THREAD

**Issue by pavm035** [SwiftGen/SwiftGen#1072]
Hi,

Recently we did upgrade SDK from 5.3.0 to 6.6.2 and updated yml files accordingly, but looks like Generated code for assets is changed and the following code is not valid anymore. Would you please let us know what do we fix to keep the code same as before

Valid in v5.3.0
Asset.Icon.EmergencyAlert.alertGray.image,

Error in 6.6.2:
Asset.Icon.EmergencyAlert.alertGray.image

Error: Type 'Asset' has no member 'Icon'

yml config
```yml
strings:
  inputs: Common/Resources/Localizable.strings
  outputs:
    templateName: structured-swift5
    output: Common/Resources/Strings.swift
    params:
      enumName: LocalizedString

xcassets:
  inputs: Common/Resources/Assets.xcassets
  outputs:
    templateName: swift5
    output: Common/Resources/Images.swift
    params:
      enumName: Asset.swift
```

Code change

```swift
// Before
internal enum Asset {
  internal enum Button {
    internal static let disclaimerClose = ImageAsset(name: "DisclaimerClose")
  }
...
}

// After
internal enum Asset {
  internal static let disclaimerClose = ImageAsset(name: "DisclaimerClose")
}
```
