### ISSUE TITLE
The SwiftGen configuration automatically substitutes fileprivate in the initialization of ColorAsset

### ISSUE THREAD

**Issue by Az-Su** [SwiftGen/SwiftGen#1086]
The SwiftGen configuration automatically **substitutes** fileprivate in the initialization of ColorAsset
The problem is that the SwiftGen configuration file puts the fileprivate access modifier to the init field. I can change it manually to public. However, after the next run of the configuration, it will change init again. How can this problem be solved?
**Here is what is written in the configuration file**:
```
xcassets:
  - inputs:
    - Images.xcassets
    outputs:
    - templateName: swift5
      output: AlmazImages.swift
      params:
        enumName: AlmazImages
        publicAccess: true
        forceProvidesNamespaces: true
        bundle: Almaz.resourcesBundle
  - inputs:
    - Colors.xcassets
    outputs:
    - templateName: swift5
      output: AlmazColors.swift
      params:
        enumName: AlmazColors
        publicAccess: true
        forceProvidesNamespaces: true
        bundle: AlmazUI.resourcesBundle
```

**How it should be:**

```
init(name: String) {
    self.name = name
  }
```
**After running the config file:**
```
fileprivate init(name: String) {
    self.name = name
  }
```
