### ISSUE TITLE
Adding Extra parameter when running SwiftGen through Xcode

### ISSUE THREAD

**Issue by amornn** [SwiftGen/SwiftGen#1087]
SwiftGen v6.6.2 (Stencil v0.15.1, StencilSwiftKit v2.10.1, SwiftGenKit v6.6.2)
MacOS Sonoma M1 Pro, Xcode 15

Run script Phase in Aggregate Target
<img width="1262" alt="Screenshot 2023-10-19 at 12 38 13" src="https://github.com/SwiftGen/SwiftGen/assets/7057693/552b345a-c8e2-4fd4-9e93-00ac90e42edf">

Running `SwiftGen` command on terminal 
<img width="1296" alt="Screenshot 2023-10-19 at 12 37 28" src="https://github.com/SwiftGen/SwiftGen/assets/7057693/decebc9b-d23b-4291-8ea2-17b072826197">

Running `SwiftGen` from Aggregate target in Xcode 
<img width="1300" alt="Screenshot 2023-10-19 at 12 36 58" src="https://github.com/SwiftGen/SwiftGen/assets/7057693/a76b55b1-aea7-488a-92af-fae11cf543ba">

Config:
```
xcassets:
  inputs:
    - CoreUIModule/CoreUIModule/Assets.xcassets
  outputs:
    - templateName: swift5
      params:
        publicAccess: N/A
        forceProvidesNamespaces: true
      output: CoreUIModule/CoreUIModule/Generated/Assets.swift

ib:
  inputs:
    - .
  outputs:
    - templateName: scenes-swift5
      output: DGW/Generated/Storyboards.swift

```
