### ISSUE TITLE
Support a `.swiftgen.yml` file to provide parameters

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#293]
Similar to what Sourcery does with `.sourcery.yml`

Example:

```yaml
output_dir: Sources/Generated
images:
  template: swift3
  params:
    enumName: Images
  source: Sources/Assets.xcasset
  output: images.generated.swift
strings:
  template: swift3
  source: Sources/Base.lproj/Localizable.strings
  output: strings.generated.swift
```

Then the use can just call `swiftgen` in their Build Phase, and it will read the arguments from the `.swiftgen.yml` file found in the current directory, or in the directory specified by `--config <path>` if specified.

_Note: `output_dir` would be an optional key; if present, it will be used as a prefix for all `output` keys in the subdirectories to avoid repeating any common prefix path everywhere._

**Comment by djbe** [comment]
Can you repeat keys such as `strings`? Depending on the use case/template/..., some of those might be repeated.

**Comment by AliSoftware** [comment]
Yeah, I guess any parameter that is repeatable should be repeatable in the YAML too. I think the nicest way to do that would be to allow that parameter to be an array instead of a dictionary or string (and if it's not an array, make it as if it was an array with one element):

```yaml
strings:
  - template: swift3
    source:
      - Sources/Base.lproj/Localizable.strings
      - Sources/Base.lproj/AnotherTable.strings
    output: strings.generated.swift
  - template: swift3
    source: Sources/Base.lproj/Errors.strings
    params:
      enumName: ErrorsL10n
    output: strings.generated.swift
```
