### ISSUE TITLE
Support for @available when generating storyboard file

### ISSUE THREAD

**Issue by damirstuhec** [SwiftGen/SwiftGen#353]
I have a custom Siri-related view controller defined with `@available(iOSApplicationExtension 11.0, *)` prefix. The generated storyboard file has build errors because of the availability of that view controller.
Is generating enum cases with `@available` prefixes currently supported in SwiftGen or is there a way to add this functionality to a custom template? Thanks!

**Comment by djbe** [comment]
Do you actually want to access this VC using SwiftGen generated code? If not, you can move it to a separate storyboard, and put it in a path that SwiftGen won't search.

Otherwise, in a custom template, you could always check the name of the scene, and if it matches yours, skip the code generation.

**Comment by damirstuhec** [comment]
@djbe Yes, I would like to access this VC using SwiftGen generated code. I guess what I want is adding `@available` to the generated enum case...

**Comment by djbe** [comment]
Right, so make a custom template (https://github.com/SwiftGen/templates/blob/master/Documentation/Creating-your-templates.md), and as I mentioned before, match your scene by name.

You can wrap these lines https://github.com/SwiftGen/templates/blob/master/templates/storyboards/swift4.stencil#L89-L91 in an if test, something like: 
```
{% if scene.identifier == "YourExtensionSpecificVC" %}
...
{% endif %}
```

For more info on how to write templates, please check the [Stencil docs](http://stencil.fuller.li), the [StencilSwiftKit docs](https://github.com/SwiftGen/StencilSwiftKit) and the [SwiftGenKit docs](https://github.com/SwiftGen/SwiftGenKit).
FYI, this is something SwiftGen won't be able to do (in a built-in way), because it depends on something in your code.

**Comment by damirstuhec** [comment]
@djbe `{% if scene.identifier == "YourExtensionSpecificVC" %}` will suffice. Thank you!

**Comment by AliSoftware** [comment]
The only generic way we could think of suggesting to support this rather to depend on the `scene.identifier == "TheName"` (especially in case you have more than one or two target-specific storyboards is to have separate tailored templates for each target and put those storyboards in separate folders.

This way you could do:
```yaml
storyboards:
  - paths: MainTarget/
    templateName: swift3
    output: MainTarget/Generated/Storyboards.swift
  - paths: AppExtensionTarget/
    templatePath: AppExtensionTarget/storyboards-custom-template.stencil
    output: AppExtensionTarget/Generated/Storyboards.swift
```
And then have `storyboards-custom-template.stencil` add that `@available(…)` annotation unconditionally (because it will only parse storyboards in the folder where they need it)
