### ISSUE TITLE
"Custom" resource type

### ISSUE THREAD

**Issue by ethanjdiamond** [SwiftGen/SwiftGen#359]
**Motivation:**
I'm currently using SwiftGen for Strings, Colors and Images. Being able to write your own templates makes it super flexible and really enjoyable to use. One limitation I've hit is that I also want to generate gradients, which would just a list of colors. I'd like to be able to have a file that I define them in like I do colors, and then to have it generate my gradients for me.

**Suggestion:**
It would be nice to have a "Custom" resource. It'd be nice in my yml file to be able to set on or more of these:

```
custom:
    templatePath: [REQUIRED]
    type: "txt"
    paths: [REQUIRED]
    output: [REQUIRED]
```

Where it would parse the keys and values from my file, and let me templatize them through SwiftGen.

I've also noticed you're getting a lot of requests for things like nibs, free-floating images, etc. While they're waiting for you, you could support their needs in the meantime with a custom template:

```
custom:
    templatePath: [REQUIRED]
    type: "file"
    paths: [REQUIRED] (This would be a regex, ex: *.png)
    output: [REQUIRED]

```

In the templates, depending on the type, these would be exposed as "object" objects with either a "key" and "value" or just a "value".
