### ISSUE TITLE
Config file: flags are incorrectly interpreted

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#434]
Some of our templates accept "flags", for example the storyboards template accepts a `ignoreTargetModule ` flag:
```yaml
input_dir: Application/Resources
output_dir: Application/Sources/Generated/SwiftGen
storyboards:
  paths: .
  templateName: swift4
  output: Storyboards.swift
  params:
    module: Ambassify
    ignoreTargetModule: true
```

Our current [documentation](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/ConfigFile.md) doesn't specify how flags should be set, so I'm just assuming it should be done as above. The problem is, no matter what value for `ignoreTargetModule` is given (`true`, `false`), the output of `swiftgen config lint` is always:
```bash
$ swiftgen storyboards -t swift4 --param module=Ambassify --param ignoreTargetModule -o Application/Sources/Generated/SwiftGen/Storyboards.swift Application/Resources
```
