### ISSUE TITLE
SwiftLint rules

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#446]
To encourage users to use SwiftGen instead of the String-based APIs, it would be nice to have SwiftLint rules that users can enable for their project.

1) Here's what I have for now, using custom rules and RegEx:

```yml
custom_rules:
  swiftgen_assets:
    name: "SwiftGen Assets"
    regex: '(UIImage|UIColor)(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
    message: "Use Asset.<asset> instead"
  swiftgen_colors:
    name: "SwiftGen Colors"
    regex: '(UIColor(\.init)?|#colorLiteral)\(((red|displayP3Red):.+?,green:.+?,blue:.+?,alpha:.+?)|(white:.+?,alpha:.+?)|(hue:.+?,saturation:.+?,brightness:.+?,alpha:.+?)\)'
    message: "Use ColorName.<color> instead"  
  swiftgen_fonts:
    name: "SwiftGen Fonts"
    regex: 'UIFont(\.init)?\(name: ?"?.+"?, ?size:.+?\)'
    message: "Use FontFamily.<family>.<variant>.size(<size>) instead"
  swiftgen_storyboards:
    name: "SwiftGen Storyboards"
    regex: '(UIStoryboard\(name: ?".+"?, ?bundle:)|(instantiateViewController\(withIdentifier:.+?\)|instantiateInitialViewController\(\)'
    message: "Use StoryboardScene.<storyboad>.<scene>.instantiate() instead"
```

2) I haven't tested them all (that's just a first draft), I can see in another project that it detects assets and Fonts, but didn't test the other ones just yet), so it's quite open for improvement and for adding rules for other stuff

3) Note that these are `custom_rules`, which use Regular Expressions to do the matching. It would be even better to create a PR in SwiftLint to add proper AST-based rules, so that it would analyse the semantics and not the text (allowing the rules to match even if there are some comments in-between the parameters, etc)

---

Next steps:

* **Feel free to improve those `custom_rules` and add or fix the regular expressions used above**, so that we end up with a nice set of custom rules that we could share with all users in SwiftGen's wiki
* Create a wiki page to host those custom rules for people wanting to use them in their project, until we have time to make an AST-based rule in SwiftLint via a PR
* Create a PR in SwiftLint to add the AST-based rules for each type of asset covered by SwiftGen, making those rules more resilient and robust than the RegEx-based ones above.

**Comment by djbe** [comment]
The nice thing about (AST) SwiftLint rules is that we could provide autocorrect functionality, which would be 🔥

**Comment by AliSoftware** [comment]
![mindblown](https://user-images.githubusercontent.com/216089/42334352-5d653ea8-807d-11e8-885d-556aee432d6b.gif)

**Comment by djbe** [comment]
Storyboard segues:

```yaml

  swiftgen_storyboard_segue_perform:
    name: "SwiftGen Storyboard Segue Identifier"
    regex: 'performSegue\(withIdentifier: ?"?.+"?, ?sender:.+\)'
    message: "Use perform(segue: StoryboardSegue.<storyboard>.<segue>, sender: <sender>) instead"
    severity: error
  swiftgen_storyboard_segue_prepare:
    name: "SwiftGen Storyboard Segue Prepare"
    regex: 'segue.identifier'
    message: "Use StoryboardSegue.<storyboard>(segue) instead"
    severity: error
```

Thoughts?
