### ISSUE TITLE
You must specify a template name (-t) or path (-p). error for config

### ISSUE THREAD

**Issue by Alexey-Matjuk** [SwiftGen/SwiftGen#470]
Following command works for me:
```sh
$ swiftgen/bin/swiftgen strings -t flat-swift4 Sources/Resources/en.lproj/Localizable.strings --output Generated.swift
```
But this one not:
```sh
$ swiftgen/bin/swiftgen
Linting swiftgen.yml
You must specify a template name (-t) or path (-p).

To list all the available named templates, use 'swiftgen templates list'.
```
As i understand this error should appear only when you don't use config file, but I see it even with a config. Please help.

My config is:
```
strings:
  paths: Sources/Resources/en.lproj/Localizable.strings
  outputs:
    - templateName: flat-swift4
      output: L10n-Constants.swift
```
I'm using [5.3.0](https://github.com/SwiftGen/SwiftGen/releases/tag/5.3.0) version of SwiftGen
