### ISSUE TITLE
Is Swift 4.2 supported yet?

### ISSUE THREAD

**Issue by BalestraPatrick** [SwiftGen/SwiftGen#471]
As the title says, I am running Xcode 10 beta 6 and this is my configuration:
```yml
strings:
  paths:
    - Tweetometer/en.lproj/Localizable.strings
  templateName: structured-swift4
  output: Generated/LocalizedStrings.swift
xcassets:
  paths:
    - Tweetometer/Assets.xcassets
  templateName: swift4
  output: Generated/Images.swift
```

When running as a run script phase or via the command-line the errors is: `File Generated not found.`

I assume that an error occurs and the file is not generated in the correct folder?
