### ISSUE TITLE
Swiftgen configuration file

### ISSUE THREAD

**Issue by TarekSalama** [SwiftGen/SwiftGen#477]
I have this `swiftgen.yml` configuration file:
```
fonts:
  paths: 
    - Resources/Fonts
  outputs:
    - templateName: swift4
    - output: Managers/FontManager.swift
colors:
  paths: 
    - Resources/Colors.txt
  outputs:
    - templateName: swift4
    - output: Managers/ColorManager.swift
xcassets:
  paths:
    - Resources/Assets.xcassets
  outputs:
    - templateName: swift4
    - output: Managers/ImageManager.swift
```

and I keep getting the following error every time I run `swiftgen` from the terminal:
```
You must specify a template name (-t) or path (-p).

To list all the available named templates, use 'swiftgen templates list'
```

What am I missing here? I have the homebrew version which does a system-wide installation.
