### ISSUE TITLE
Documentation should match current stable release

### ISSUE THREAD

**Issue by skagedal** [SwiftGen/SwiftGen#507]
I integrated SwiftGen using the CocoaPods approach, which game me the following:

```
$ ./Pods/SwiftGen/bin/swiftgen --version
SwiftGen v5.3.0 (Stencil v0.10.1, StencilSwiftKit v2.4.0, SwiftGenKit v2.2.0)
```

I then tried a simple `swiftgen.yml` as per the README or [ConfigFile.md](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/ConfigFile.md):

```
input_dir: MyProject
output_dir: MyProject/Generated
strings:
  inputs: Main/Localizable.strings
  outputs: 
    - templateName: structured-swift4
      output: LocalizableStrings.swift
```

The output of `swiftgen config lint` is:

```
Linting swiftgen.yml
Missing entry for key strings.paths.
```

I read in ConfigFile.md that this `paths` key is now deprecated. I assume that this describes a future version? Expected behavior imo is that the documentation in "master" describes the behavior in released version. 

Regards, Simon
