### ISSUE TITLE
Unknown filter error after launch by Mint

### ISSUE THREAD

**Issue by alphatroya** [SwiftGen/SwiftGen#526]
There is a failure after the attempt to launch SwiftGen by Mint.
```
mint run SwiftGen/SwiftGen
🌱  Finding latest version of SwiftGen
🌱  Resolved latest version of SwiftGen to 6.0.0
🌱  SwiftGen 6.0.0 already installed
🌱  Running swiftgen 6.0.0...
Unknown filter 'escapeReservedKeyword'. Found similar filters: 'escapeReservedKeywords'.
```
I've installed the `libxml2` package (version 2.9.7).
The error is disappeared if I try to launch the brew version.

**Comment by AliSoftware** [comment]
Thanks for reporting the issue!

That's strange, that error seems to suggest that the templates bundled via Mint are different from the ones bundled by brew, one using `escapeReservedKeyword` and the other using `escapeReservedKeywords`. Or maybe that's Mint & Brew not pointing to the same version of `StencilSwiftKit` (which is the pod where those filters are defined)… We'll need to investigate

**Comment by djbe** [comment]
The `escapeReservedKeywords` has always had that name, I don't think we've ever had that error?

@alphatroya are you using a custom template? I assume you're using a config file, could you post that please?

**Comment by alphatroya** [comment]
No, I use bundled templates, my config is here.

```yaml
input_dir: Project/Resources/
output_dir: Project/Classes/UIKit/Extensions/
strings:
    inputs: ru.lproj/Localizable.strings
    outputs:
        templateName: structured-swift4
        output: Strings.swift
xcassets:
    inputs: Assets.xcassets
    outputs:
        templateName: swift4
        output: Images.swift
```
