### ISSUE TITLE
Use of undeclared type 'SwiftGen' in generated Scenes.swift

### ISSUE THREAD

**Issue by yoiang** [SwiftGen/SwiftGen#556]
* SwiftGen v6.0.2 (Stencil v0.13.1, StencilSwiftKit v2.7.1, SwiftGenKit v6.0.2)
* Xcode Version 10.0 (10A255)
* iOS Deployment Target 11.0

Background:
I am working on a project that has a number of Storyboard files whose file name matches the class name of the initial view controller. IE: `ExampleViewController.storyboard`'s initial view controller is of type `ExampleViewController`.

I haven't appended an error because it includes proprietary information. If the cause of this issue isn't obvious I can recreate the situation in an example project!

**Comment by AliSoftware** [comment]
Hi

What template are you using and what parameters did you pass to it in your `swiftgen.yml` config file?

**Comment by yoiang** [comment]
Our `swiftgen.yml` file is:

```yml
ib:
  inputs:
    - ./Project/
  outputs:
  - templateName: scenes-swift4
    output: ./Project/Generated/Storyboard Scenes.swift
  - templateName: segues-swift4
    output: ./Project/Generated/Storyboard Segues.swift
```

**Comment by AFcgi** [comment]
I have similar the same problem. I use the templates from current SwiftGen like:
```
ib:
  inputs: Storyboards
  outputs:
    - templateName: scenes-swift4
      output: Scenes.swift
    - templateName: segues-swift4
      output: Segues.swift
```

The SwiftGen version 6.x generate the following lines of code:
```
internal static let viewController = SceneType<Pod_Example.ViewController>(storyboard: Main.self, identifier: "ViewController")
```

In earlier versions SwiftGen imports the current project like `import Pod_Example`. After SwiftGen 6.x it's not possible for me to setup the import statement. I can only use the parameter `ignoreTargetModule: true`. But I don't know if this will have consequences because I use SwiftGen inside a pod. Do you have any ideas how can I fix this issue?
