### ISSUE TITLE
Multiple inputs and outputs files for `strings`

### ISSUE THREAD

**Issue by kacper1703** [SwiftGen/SwiftGen#649]
My goal is to have separate translations files for my main app and Siri Extension.

I have in my `swiftgen.yml` file:
```
strings:
  inputs: SiriExtension/Errors/en.lproj/Errors.strings
  outputs:
    templateName: flat-swift4
    output: SiriExtension/Errors/Errors.swift
    parameters:
        enumName: SiriError

strings:
  inputs: MainApp/Resources/en.lproj/Localizable.strings
  outputs:
    templateName: flat-swift4
    output: MainApp/Constants/Strings.swift
```

Despite including both of the `strings` commands in the file, only one is executed. 
`swiftgen config lint` prints:
```
> 1 entry for command strings:
 $ swiftgen strings --templateName flat-swift4 --output MainApp/Constants/Strings.swift MainApp/Resources/en.lproj/Localizable.strings
```

What am I doing wrong?

**Comment by djbe** [comment]
Check the [Configuration File Format](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/ConfigFile.md#configuration-file-format) documentation, for multiple invocations of the same command, you'll want something like:

```yaml
strings:
  - inputs: SiriExtension/Errors/en.lproj/Errors.strings
    outputs:
      templateName: flat-swift4
      output: SiriExtension/Errors/Errors.swift
      parameters:
        enumName: SiriError
  - inputs: MainApp/Resources/en.lproj/Localizable.strings
    outputs:
      templateName: flat-swift4
      output: MainApp/Constants/Strings.swift
```
