### ISSUE TITLE
SwiftGen does not work if two different outputs with same input

### ISSUE THREAD

**Issue by Igor-Palaguta** [SwiftGen/SwiftGen#650]
Just last color command is executed
```yaml
xcassets:
  inputs:
    - Color.xcassets
  outputs:
    templatePath: UIColor.stencil
    output: UIColor+AssetCatalog.swift

xcassets:
  inputs:
    - Color.xcassets
  outputs:
    templatePath: SwiftUI-Color.stencil
    output: Color+AssetCatalog.swift
```

```
swiftgen --version
SwiftGen v6.1.0 (Stencil v0.13.1, StencilSwiftKit v2.7.2, SwiftGenKit v6.1.0)
```
