### ISSUE TITLE
Add SVG parser

### ISSUE THREAD

**Issue by iacopo87** [SwiftGen/SwiftGen#676]
Hello,

In my project I'd like to make my SVGs type-safe to use, like the other images in xcassets.

Right now however the available parsers doesn't allow SVG files so I would like to know if you have any plans to support this kind of resource in the future or you suggest me to create a custom parser and template?

My idea is to be able to write something like this in the `swiftgem.yml`
````
svg:
    inputs: my/svg/folder
    outputs:
        templateName: my/template/name
        output: Generated/Svgs.swift
````

Any suggestions are more them welcome :)
