### ISSUE TITLE
Optionally skip metadata generation for JSON/Yaml parsers

### ISSUE THREAD

**Issue by marcelofabri** [SwiftGen/SwiftGen#700]
When profiling parsing JSONs (Lottie animations), I've noticed that most of the time is spent generating the `metadata` field, although my template doesn't use it at all.

By commenting [this line](https://github.com/SwiftGen/SwiftGen/blob/develop/Sources/SwiftGenKit/Stencil/YamlContext.swift#L36), I was able to improve the duration from ~750ms (using `JSONSerialization`, see #698) to ~100ms.

Since figuring out whether we need to parse it or not based on the template would be tricky, I propose that we add a key to `ConfigEntryOutput` named `includeMetadata` that will be `true` by default.

The configuration file would look like this:

```yml
json:
  inputs:
    - Assets/Lottie/
  outputs:
    - templatePath: templates/lottie.stencil
      output: Generated/Lottie.swift
      includeMetadata: false # or should it be `skipMetadata` instead?
```
