### ISSUE TITLE
Problem with generating Assets enum

### ISSUE THREAD

**Issue by idevAgg** [SwiftGen/SwiftGen#744]
I use SwiftGen for generate sources for localization and assets in my project, but something went wrong few days ago. Asset's enum not generating after the project building. There is no problems with .strings files, only with .xcassets. Maybe you know in which case it can be? Usage:  
.sh file:
<img width="610" alt="Снимок экрана 2020-07-07 в 13 51 56" src="https://user-images.githubusercontent.com/50491957/86770255-14189880-c059-11ea-9c8c-f5732fb98430.png">
Build Phases
<img width="1791" alt="Снимок экрана 2020-07-07 в 13 52 57" src="https://user-images.githubusercontent.com/50491957/86770332-35798480-c059-11ea-9064-6b549d73e0c8.png">
source  files: 
<img width="231" alt="Снимок экрана 2020-07-07 в 13 53 48" src="https://user-images.githubusercontent.com/50491957/86770445-5cd05180-c059-11ea-947c-79d2d562be32.png">

**Comment by djbe** [comment]
What version of SwiftGen are you using? Because if it's SwiftGen 6.2 or higher, we obsoleted (removed) the `swift3` templates.

Also, it's highly recommended to use a configuration file:
- You can `lint` your setup and see if everything is correct (wrong paths, missing templates, outdated commands, etc..)
- You get a performance boost because SwiftGen can run parsers in parallel

**Comment by idevAgg** [comment]
Podfile.lock:
- SwiftGen (6.2.1) 
What do you recommend? Do you have some new template for assets? Or just use some specify version of SwiftGen?

**Comment by djbe** [comment]
An example config file in your  case (based on what I can see above), would be:
```yaml
input_dir: w2w/Resources
output_dir: w2w/Resources
strings:
  inputs: en.lproj/Localizable.strings
  outputs:
    templateName: structured-swift5
    output: L10n.swift
xcassets:
  inputs: Assets.xcassets
  outputs:
    templateName: swift5
    output: Assets.swift
```

A quick how-to about configuration files can be found here: https://github.com/SwiftGen/SwiftGen#configuration-file

Note: I've taken the liberty of choosing `swift5` templates. There aren't any (big) differences between the `swift4` and `swift5` templates.
