### ISSUE TITLE
Parser `default` does not exist.

### ISSUE THREAD

**Issue by artem-voir** [SwiftGen/SwiftGen#759]
After updating swiftgen to the latest version (6.2) and launch `swiftgen config lint`, I've occurred error: 
```
Parser `default` does not exist.
```

My config file
```
default: &modulename TestModule
input_dir: Resources
output_dir: src/Generated/
plist:
  inputs: Assets
  outputs:
    - templatePath: template.stencil
      output: Generated.swift
      params:
        modulename: *modulename
```

So, as you can see, earlier I used `default: &modulename TestModule` for pass variable to stencil, f.e.
```
import UIKit

extension UIView {
    static let {{param.modulename|lowerFirstWord}}: String = "{{param.modulename}}"
}
```

How can I use variable now?

**Comment by djbe** [comment]
Our config file format only supports the following keys at the root level: `input_dir`, `output_dir`, `color`, `coredata`, `fonts`, `ib`, `json`, `plist`, `strings`, `xcassets` and `yaml`. Besides `input_dir`/`output_dir`, all the other keys correspond to parsers. It's checking/trying for a `default` parser, and can't find any with that name.

While using anchors/references is a nice trick to avoid repeating your modulename, it's currently unsupported by our Config parser (Yams probably correctly parses it, I mean our handling of the parsed data).

**Comment by djbe** [comment]
So to clarify, to get it to work, change your config to this:

```yaml
input_dir: Resources
output_dir: src/Generated/
plist:
  inputs: Assets
  outputs:
    - templatePath: template.stencil
      output: Generated.swift
      params:
        modulename: TestModule
```
