### ISSUE TITLE
Plist: generates incorrect Bool values

### ISSUE THREAD

**Issue by kacper1703** [SwiftGen/SwiftGen#775]
### Environment
- Xcode 12.0 GM
- SwiftGen 6.2.1 (via CocoaPods)

### Repro steps
- Create a plist `Example.plist`
- In the root dictionary add a Bool key `IsTestEnabled` with value `false` (which Xcode corrects to **0** and it cannot be bypassed)
- In swiftgen.yml:
```yaml
plist:
  - inputs: [PATH]/Example.plist
    outputs:
      - templateName: inline-swift5
        output: ExamplePlistKeys.swift
        params:
          enumName: "PlistKeys"
```

### Result
Compiler can't accept `0` as a Boolean value.
```swift
internal enum PlistKeys {
  internal enum Example {
    internal static let isTestEnabled: Bool = 0
  }
```

### Expected result
Boolean values are converted from `0` and `1` to `false` and `true`, respectively.
