### ISSUE TITLE
Unable to load PLIST at path (Inside nested folders)

### ISSUE THREAD

**Issue by lex-shvets** [SwiftGen/SwiftGen#798]
I am trying to generate my info.plist and the generated file has a wrong path and therefor crashes.

My swiftgen file:
```
...
plist:
  inputs:
      - ProjectName/Resources/Configs/info.plist
  outputs:
    templateName: runtime-swift5
    output: ProjectName/Resources/Generated/Plist.swift
```

Inside generated file I have a path: `private static let _document = PlistDocument(path: "info.plist")`

When I run my app it crashes because of: `Fatal error: Unable to load PLIST at path: info.plist`

My plist is in nested folders so of course path is wrong. 

path to the plist is:
`      - ProjectName/Resources/Configs/info.plist`
