### ISSUE TITLE
Separator parameter in StringParser doesn't take any effect

### ISSUE THREAD

**Issue by chaserunner** [SwiftGen/SwiftGen#799]
Hi. I'm using SwiftGen 6.4.0.

My `swiftgen.yml` looks like: 
```yaml
input_dir: MyProj/Resources/
output_dir: MyProj/Resources/
strings:
  inputs: Strings/en.lproj
  outputs:
    - templateName: structured-swift5
      output: Strings/Strings.swift
      params:
        separator: "_"

...
```

My strings file example:
```text
"underscore_test_structure" = "test";

"dot.test.structure" = "test";
```

The resulting struct is: 
```swift
internal enum L10n {
  /// test
  internal static let underscoreTestStructure = L10n.tr("Localizable", "underscore_test_structure")

  internal enum Dot {
    internal enum Test {
      /// test
      internal static let structure = L10n.tr("Localizable", "dot.test.structure")
    }
  }
}
```

I expect the final struct to be the opposite. Am I getting something wrong or this is an issue?

**Comment by djbe** [comment]
Ah good try, you almost had it right! You need to set the separator as a parser option:
```yaml
strings:
  inputs: Strings/en.lproj
  outputs: ...
  options:
    separator: "_"
```

There are 2 ways to configure SwiftGen:
- Parser options, which modify how **input** data is processed (such as `separator`)
- Template parameters, which modify the **output** that will be generated (such as `publicAccess`)
