### ISSUE TITLE
6.4.0 breaks l10

### ISSUE THREAD

**Issue by mycroftcanner** [SwiftGen/SwiftGen#804]
I don't know what you have changed but SwiftGen won't generate my strings anymore... It was working perfectly in previous versions 

```
strings:
  inputs: Localizable.strings
  outputs:
    templateName: structured-swift4
    output: Strings.swift
```
