### ISSUE TITLE
How to specify -publicAccess in the config yaml?

### ISSUE THREAD

**Issue by MikeChongCan** [SwiftGen/SwiftGen#825]
I can see only `swiftgen run coredata` supports custom params, such as `--param publicAccess`.

Any way to write this one into the config yaml?

**Comment by djbe** [comment]
Something like this:

```yaml
coredata:
  - inputs: ...
    outputs:
      - templateName: ...
        output: ...
        params:
          publicAccess: true
```

You can read more about the config file [here](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/ConfigFile.md). For example, you can `lint` your config file and see which "invocations" of SwiftGen will happen behind the scenes.
