### ISSUE TITLE
Questions: How to use SwiftGen for multiple languages ?

### ISSUE THREAD

**Issue by qureship786** [SwiftGen/SwiftGen#829]
I am using SwiftGen and associated localization for the first time so trying to understand it's usage in case of multiple languages. Basically I have to add support for other languages besides English (default already present) in an existing project. Currently the project has L10n.swift file containing the english language strings constants grouped . The swiftgen.yml file has an entry for strings as below:

```
strings:
  inputs: path/to/Localization/en.lproj
  filter: .+\.strings$
  outputs:
    - templateName: structured-swift4
      output: path/to/Localization/L10n.swift
```

Below are some of my questions:

- I have added two other language's Localizable.strings file in their respective .proj files, how should I modify swiftgen.yml file to add entries for the two languages ? What naming convention we have to use for adding name for corresponding Lxxn.swift file ?
- Once user selects a language from Settings application and launch my application, how I am going to determine which Lxxn.swift will be used ?
- Does the entire project that has a scattered usage of L10n has to be updated and instead replaced with some other wrapper method that returns current language specific string and if not found then defaults to English language ?
