### ISSUE TITLE
Output Font file (generated) is empty!

### ISSUE THREAD

**Issue by razor313** [SwiftGen/SwiftGen#830]
I've used  `SPM` in order to add `SwiftGen` to my project and I've added the fonts according to [the Apple documention](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_appl).

![Screen Shot 2021-04-20 at 2 21 27 AM](https://user-images.githubusercontent.com/26047366/115307940-34948800-a17f-11eb-9caa-b9b05d5e8cff.png)

I don't get any error during the build phase and Assets.generated.swift file would be generated all enums.
But after it the output file of the font is empty.
Here is the `swiftgen.yml` file in which I use.
```
input_dir: ${PROJECT_DIR}/PROJECT_NAME/Resources/
output_dir: ${PROJECT_DIR}/PROJECT_NAME/Resources/

xcassets:
  inputs: Assets.xcassets
  outputs:
    templatePath: "${PROJECT_DIR}/Tools/SwiftGenerator/.build/checkouts/SwiftGen/templates/xcassets/swift5.stencil"
    output: Assets.generated.swift

fonts:
  inputs: Fonts
  outputs:
    templatePath: "${PROJECT_DIR}/Tools/SwiftGenerator/.build/checkouts/SwiftGen/templates/xcassets/swift5.stencil"
    output: Fonts.generated.swift
```

Here is the content of the Fonts.generated.swift file:

```
// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

// No assets found
```
