### ISSUE TITLE
Duplicate file of the same type for table "Localizable"

### ISSUE THREAD

**Issue by IanHoar** [SwiftGen/SwiftGen#835]
Hey there, I'm testing the SwiftGen integration on my project and I'm getting this error when trying to generate my strings files:

`Duplicate file of the same type for table "Localizable"`

I'd like to keep the folder structure and filenames as they're being generated by Lokalise, but I'm wondering if there is some way to have the strings files at different paths not show as duplicates when I try to generate `Strings.swift`

This is my SwiftGen.yml:

```
strings:
  inputs: ../Resources
  outputs:
    - templateName: structured-swift5
      output: ../Resources/Generated/Strings.swift
      params:
          publicAccess: 1
```

here's my Package.swift in case that is playing a part:

```
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "LocalizationKit",
    defaultLocalization: "en",
    products: [
        .library(
            name: "LocalizationKit",
            targets: ["LocalizationKit"]),
    ],
    targets: [
        .target(
            name: "LocalizationKit",
            path: "Resources",
            resources: [.copy("Resources")]
        )
    ]
)
```
and this is my folder structure: 

<img width="278" alt="Screen Shot 2021-05-11 at 11 56 06 AM" src="https://user-images.githubusercontent.com/967712/117869664-ea6b6780-b24f-11eb-9c21-ba53ea55f49e.png">

**Comment by djbe** [comment]
Right now, you're asking SwiftGen to parse all strings files in the `Resources` folder, so it'll see duplicate strings files (with the same name).

You should instead point SwiftGen at a **specific** language (ideally your development language, usually `en.lproj`). For example:

```yaml
strings:
  inputs: ../Resources/en.lproj
  outputs:
    - templateName: structured-swift5
      output: ../Resources/Generated/Strings.swift
      params:
          publicAccess: 1
```
