### ISSUE TITLE
Accessing string with percentage symbol strips it

### ISSUE THREAD

**Issue by igorkulman** [SwiftGen/SwiftGen#859]
I am using SwiftGen to generate strings with the structured swift5 template

```yaml
strings:
  inputs:
    - Source/Localization/en.lproj/Localizable.strings
    - Source/Localization/en.lproj/Localizable.stringsdict
  outputs:
    params:
      publicAccess: true
      enumName: LocalizedString
    templateName: structured-swift5
    output: Source/LocalizedString.swift
```

If I have a string that contains the percentage symbol, like

```
"percentage_symbol_test" = "Result is 100%";
```

accessing `LocalizedString.percentageSymbolTest` gives me `Result is 100` with the percentage being stripped.
