### ISSUE TITLE
separator option doesn't work in 6.5.1

### ISSUE THREAD

**Issue by dsk1306** [SwiftGen/SwiftGen#892]
Hi. I'm using SwiftGen `6.5.1`.

My `swiftgen.yml` looks like:
```yaml
strings:
  - inputs: <path to en.lproj>
    outputs:
      - templateName: structured-swift5
        output: <path to generated swift file>
        options:
          separator: "-"
```
My strings file example:
```
"Test-some1" = "Some-1";
"Test-some2" = "Some-2";
"Test-some3" = "Some-3";
"Test.some4" = "Some-4";
```
The resulting struct is:
```swift
internal enum L10n {
  /// Some-1
  internal static let testSome1 = L10n.tr("Localizable", "Test-some1")
  /// Some-2
  internal static let testSome2 = L10n.tr("Localizable", "Test-some2")
  /// Some-3
  internal static let testSome3 = L10n.tr("Localizable", "Test-some3")

  internal enum Test {
    /// Some-4
    internal static let some4 = L10n.tr("Localizable", "Test.some4")
  }
}
```
Am I missing something?
I've noticed that there is a similar issue https://github.com/SwiftGen/SwiftGen/issues/799 for `6.4.0`, but the proposed solution didn't work for me.

**Comment by dsk1306** [comment]
The `separator` option is also ignored if I use "-" as a separator.

**Comment by djbe** [comment]
Same is with #799, your `options` is at the wrong level. It should be one level up, not in the `outputs` array. These options apply to the *parsing* of the input, not to the rendering of the output template.

Like this:
```yaml
strings:
  - inputs: <path to en.lproj>
    options:
      separator: "-"
    outputs:
      - templateName: structured-swift5
        output: <path to generated swift file>
```
