### ISSUE TITLE
Inconsistent execution for multiple inputs and outputs in `strings` generation

### ISSUE THREAD

**Issue by LeviGustin** [SwiftGen/SwiftGen#894]
My situation was modularized with the need for individual Localized strings files per module so each module was independent. Referencing #649 , I implemented the following in our `swiftgen.yml` file genericized for First, Second and Third module names:

```
strings:
  inputs:
    - First/Resources/en.lproj
  outputs:
    - templatePath: BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
      output: First/Generated/Localized.swift
  inputs:
    - Second/Resources/en.lproj
  outputs:
    - templatePath: BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
      output: Second/Generated/Localized.swift
  inputs:
    - Third/Resources/en.lproj
  outputs:
    - templatePath: BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
      output: Third/Generated/Localized.swift
```

It was found that the execution for generating the outputs was inconsistent. Even when making a change in all three input files, usually the "First" would get generated and sometimes one of the other two would as well. Build logs would report `Not writing the file as content is unchanged`. Nothing we could do would shake this "unchanged" calculation. We also tried separate named `strings` blocks in the same file but that didn't help either. We did find that pairing down the inputs/outputs blocks back to a single request would get us consistent results.

To work around this, we decided to break up our `swiftgen.yml` file into individual pieces to be held in each module. This would allow us to have only one set of inputs/outputs per execution. Ie. the `swiftgen.yml` file in our First module looked like such:

```
strings:
  inputs:
    - Resources/en.lproj
  outputs:
    - templatePath: ../BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
      output: Generated/Localized.swift
```

And then the Target's build phase was updated to duplicate the run call for each file:

```
swift run --package-path BuildTools --configuration release swiftgen config run --config First/swiftgen.yml
swift run --package-path BuildTools --configuration release swiftgen config run --config Second/swiftgen.yml
swift run --package-path BuildTools --configuration release swiftgen config run --config Third/swiftgen.yml
```

I feel that there is a race condition or similar in the logic when attempting to use more than one set of inputs/outputs. 

SwiftGen: v6.5.1
Xcode: v13.1
Targeting iOS v14.0+

**Comment by djbe** [comment]
Quick sanity check: the first config you posted, it's not valid (there needs to be a `- ` before each of your inputs, so you have an array of "entries" for each parser (`strings` in your case). So it has to be something like:
```yaml
strings:
  - inputs:
      - First/Resources/en.lproj
    outputs:
      - templatePath: BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
        output: First/Generated/Localized.swift
  - inputs:
      - Second/Resources/en.lproj
...
```

Is the config you posted the one you actually use (with some name changes for example purposes)? If so, that may be your issue, as it'd be invalid.

**Comment by djbe** [comment]
Following up on my previous comment, I think the yaml parser we use, Yams (based on `libYAML`), ignores duplicate "keys". See these issues for reference: https://github.com/jpsim/Yams/issues/178 and https://github.com/yaml/libyaml/issues/166

We can't even "validate" for it in our `config lint`, as that also loads the yaml file using the same library. I'm not sure if there's an alternative 🤔

**Comment by LeviGustin** [comment]
@djbe Thank you for the catch! You were completely right in the need for `-` before the array of inputs. I got the following `swiftgen.yml` file to work:

```
strings:
  - inputs: 
    - First/Resources/en.lproj
    outputs:
    - templatePath: BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
      output: First/Generated/Localized.swift
  - inputs: 
    - Second/Resources/en.lproj
    outputs:
    - templatePath: BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
      output: Second/Generated/Localized.swift
  - inputs: 
    - Third/Resources/en.lproj
    outputs:
    - templatePath: BuildTools/SwiftGen/swiftgen-swiftui-template.stencil
      output: Third/Generated/Localized.swift
```

I also was able to revert my build phase to point to this single `swiftgen.yml` file located at the root of the project.

Please consider this issue closed and me more educated on proper YAML file formatting for array. Thank you.
