### ISSUE TITLE
Getting deprecated warnings

### ISSUE THREAD

**Issue by mrtsamma** [SwiftGen/SwiftGen#895]
``Version: 
SwiftGen v6.5.1 (Stencil v0.14.1, StencilSwiftKit v2.8.0, SwiftGenKit v6.5.1)

Getting deprecated warnings for config file but following the [SwiftGen Configuration File readme](https://github.com/SwiftGen/SwiftGen/blob/6.5.1/Documentation/ConfigFile.md#swiftgen-configuration-file)

My Config file swiftgen.yml
```
input_dir: ../../Sources/
output_dir: ../../Sources/Core/Common/Resources/

strings:
  inputs:
    - App//Localization/Base/Base.lproj
  outputs:
    - templatePath: StringsEnumGen.stencil
      output: L10n.generated.swift
    - templatePath: StringsLocalizableExtensionsGen.stencil
      output: L10n.extensions.generated.swift

xcassets:
  - inputs: Core/Common/Resources/Assets/
    filter: .+\.xcassets$
    outputs:
      - templatePath: UIImageAssetsGen.stencil
        output: UIImageAssets.generated.swift
      - templatePath: AssetsGen.stencil
        output: Assets.generated.swift
  - inputs: Core/Common/Resources/Colors
    filter: .+\.xcassets$
    templatePath: ColorsGen.stencil
    output: Colors.generated.swift
    params:
       forceProvidesNamespaces: false
       mainColorCatalog: Colors
```
Which is done accordingly to readme.
And getting console output on running command `swiftgen`
```
swiftgen: warning: xcassets: `output` is a deprecated in favour of `outputs.output`.
swiftgen: warning: xcassets: `params` is a deprecated in favour of `outputs.params`.
swiftgen: warning: xcassets: `templatePath` is a deprecated in favour of `outputs.templatePath`.
```

Not sure how to fix my config file. Is documentation out of date?

**Comment by djbe** [comment]
It's your last entry under xcassets, for your Colors catalogs, should become:
```yaml
  - inputs: Core/Common/Resources/Colors
    outputs:
      - templatePath: ColorsGen.stencil
        output: Colors.generated.swift
        params:
          forceProvidesNamespaces: false
          mainColorCatalog: Colors
```

Note that I've removed the filter, it's not needed if you're just using the default filter
