### ISSUE TITLE
"No string found" error

### ISSUE THREAD

**Issue by murabye** [SwiftGen/SwiftGen#910]
Hello I have SwiftGen v6.5.1 (Stencil v0.14.1, StencilSwiftKit v2.8.0, SwiftGenKit v6.5.1)
.yml file:
```
input_dir: ./
output_dir: ./

xcassets:
  inputs:
    - ./../Resources/en.lproj/SimpleStrings.strings
    - ./../Resources/en.lproj/PluralStrings.stringsDict
  outputs:
    - templatePath: ./strings.stencil
      params:
        forceProvidesNamespaces: true
        publicAccess: true
      output: ./../StringDict.swift
```
Stencil: copy structured-swift5;
xCode: 13.2.1, m1;
command:
`arch -x86_64 swiftgen config run --config StringDict/Sources/StringDict/SwiftGen/string_swiftgen.yml`;
SimpleStrings.strings:
`"cancel" = "cancel";`
Package config:
```
import PackageDescription
let package = Package(
	name: "StringDict",
	defaultLocalization: "en",
	platforms: [.iOS(.v13)],
	products: [
		.library(
			name: "StringDict",
			type: .dynamic,
			targets: ["StringDict"])
	],
	dependencies: [ ],
	targets: [
		.target(
			name: "StringDict",
			dependencies: [ ],
			resources: [.process("Resources")]),
		.testTarget(
			name: "StringDictTests",
			dependencies: ["StringDict"])
	]
)
```
Package structure:
https://i.ibb.co/F0mj7gq/2021-12-22-15-24-10.png

Please help what I doing wrong?
