### ISSUE TITLE
Unable to parse JSON for colors

### ISSUE THREAD

**Issue by niklassaers** [SwiftGen/SwiftGen#933]
Hi, I have an asset catalog with only one asset, the AccentColor. Here is its Contents.json:

```
{
  "colors" : [
    {
      "color" : {
        "color-space" : "display-p3",
        "components" : {
          "alpha" : "1.000",
          "blue" : "0.820",
          "green" : "0.890",
          "red" : "0.871"
        }
      },
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```

When SwiftGen sees this, it says: An error occurred: error: Unable to parse file at `/Users/niklas/Projects/SwiftGenTest/Resources/Colors.xcassets/AccentColor.colorset/Contents.json. Invalid structure, must be an object with string values.` As you can see from above, the JSON looks to have a fine structure. All generated via Xcode. Any idea what may be causing the error?

My swiftgen.yml looks like:
```
colors:
  inputs:
    - Resources/Colors.xcassets
  outputs:
    - templateName: swift5
      output: Source/Generated/Color+Generated.swift

```
