### ISSUE TITLE
swiftgen files parameter preservePath not working

### ISSUE THREAD

**Issue by zangqilong198812** [SwiftGen/SwiftGen#942]
here is my yml file
```
files:
   - inputs:
       - JSON
     outputs:
       - templateName: structured-swift5
         output: Generated/Files+Generated.swift
         params:
           bundle: CECommunityBundle.bundle
           preservePath: JSON
```
and it generates files like this
internal static let likeVideoJson = File(name: "likeVideo", ext: "json", relativePath: "", mimeType: "application/json")

I hope the relativePath could be "JSON"
Can anyone tell me why swiftgen ignore the preservePath parameter?
