### ISSUE TITLE
Autogenerated `ib` code triggers warnings for Xcode 14 beta with concurrency checks

### ISSUE THREAD

**Issue by alistra** [SwiftGen/SwiftGen#946]
Xcode project with `SWIFT_STRICT_CONCURRENCY=complete` generates the following warning:

<img width="1373" alt="Screenshot 2022-06-27 at 17 05 55" src="https://user-images.githubusercontent.com/233144/175973203-36ae06f0-d682-4e09-b07e-d91c4c567566.png">

`swiftgen.yml`
```
ib:
  inputs:
    - .
  outputs:
    - templateName: scenes-swift5
      output: IBScenes+Generated.swift
    - templateName: segues-swift5
      output: IBSegues+Generated.swift
```

Probable fix is adding `@MainActor` on the protocol or the `init`.

Xcode version 14.0 beta 2 (14A5229c)
